### ISSUE TITLE
Enter Logon Data Prompt

### ISSUE THREAD

**Issue by Dev4Develop** [microsoft/aisdkforsapabap#20]
Hi Gopal,

Why am I seeing this username/password window? I see my Free subscription has ended and the API keys are disabled in Azure Open AI . Is it because of that?

![image](https://github.com/microsoft/aisdkforsapabap/assets/137146462/28482d08-c8dc-4766-9779-5c50970a9dae)

**Comment by gopalnair** [comment]
Hi @Dev4Develop ,
 The popup comes up due to failed authorization. In this case, as your API keys are disabled/resource is disabled, the authentication fails, and you are presented with a prompt.

JFYI... AI SDK for SAP supports Azure Open AI as well as **Open AI**, as you can see in the documentation website. So, if you dont have access to Azure Open AI, you can try out all the features using Open AI as well. 


Best Regards,
Gopal Nair.

**Comment by Dev4Develop** [comment]
Thanks Gopal for quick response. I tried creating Secret Key and use in the program ZP_PENGG_AZOAI_DEMO_COMPLETION. But what will be the input for other Selection Screen Parameters?

Otherwise If we have any demo program without Azure let me know.

![image](https://github.com/microsoft/aisdkforsapabap/assets/137146462/e418cf34-5a5a-4b87-a7d4-80343a677fc1)
