### ISSUE TITLE
Error in  ZP_AISDKDEMO_CHATCOMPL_SIMPLE

### ISSUE THREAD

**Issue by Subhu1992** [microsoft/aisdkforsapabap#27]
Hi, when i am trying to execute this report from SAP ( S4 2022) i am getting an error.. below are the input  ( with correct URL and Key)

![image](https://github.com/microsoft/aisdkforsapabap/assets/71837596/fd454d44-0319-49da-8ae6-cd3fee6fb730)

Error is : as below screenshot ? 
![image](https://github.com/microsoft/aisdkforsapabap/assets/71837596/353d3662-8c63-4ce0-aad2-c0838564f13a)

**Comment by gopalnair** [comment]
Hi @Subhu1992 ,
  Based on the screenshot in your question, the demo program is working as expected... this is not an error. Rather, what ever the AI Engine returned (The generated text) is what is shown in a pop up window. This means, the call succeeded.

I would recommend taking a look at the demo program code, and change the prompt that is being passed to something else (something simple to understand how it all works) 

Example : 
![image](https://github.com/microsoft/aisdkforsapabap/assets/1298551/86c88514-62a9-4b0f-9554-f3f8cf3ff963)

And here is the result I got (Yours may be different due to generated text being different). 
![image](https://github.com/microsoft/aisdkforsapabap/assets/1298551/ccb1893f-459d-48c6-94c0-c9e79b8323df)
