### ISSUE TITLE
 Azure Active Directory(AAD) auhentication not documented 

### ISSUE THREAD

**Issue by mthoger** [microsoft/aisdkforsapabap#30]
Only local authentication using keys is documented, however Azure Active Directory(AAD) is supposed to be supported. 
I'm very interested in how this is configured, as local auth and keys har disabled in out azure policies. 

home somebody can point me in the right direction.

**Comment by gopalnair** [comment]
Hi @mthoger ,
   The use of AAD token is mentioned in the following documentation page: (Initialize SDK) 
https://microsoft.github.io/aisdkforsapabap/docs/working-with-sdk/initialize_sdk#api_type


Here, we specify the api type parameter during initialization, and - instead of the key, we pass in the bearer token.

![image](https://github.com/microsoft/aisdkforsapabap/assets/1298551/14095344-b712-4271-9ae2-c88317ac9825)


While the information is available in the page, it seems like, its something that we should showcase more - perhaps just under the key based mechanism. I will work towards updating the documentation website around this.

Please let me know if the issue is resolved and you are able to use the AI SDK with AAD token.

Best Regards,
Gopal Nair.
